name: 'Python Wheels'

on:
  workflow_dispatch:
  release:
    types: ['released', 'prereleased']

env:
  PACKAGE_VERSION: "1.0.0a20.dev0"
  PACKAGE_NAME: alpaqa

jobs:
  generate-stubs:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:jammy
    env:
      HOST: 'x86_64-bionic-linux-gnu'
      CMAKE_C_COMPILER_LAUNCHER: ccache
      CMAKE_CXX_COMPILER_LAUNCHER: ccache
      CCACHE_DIR: /root/.ccache
      CONAN_HOME: /root/.conan2
    steps:
      # Git clone
      - name: Install git
        run: apt -y update && apt -y install --no-install-recommends git ca-certificates
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      # Tools
      - name: Install tools
        id: tools
        uses: ./.github/workflows/new-toolchain
        with:
          host: ${{ env.HOST }}
          with-python: true
      # Ccache
      - name: Prepare ccache directory
        run: mkdir -p "${{ env.CCACHE_DIR }}"
      - name: Cache ccache
        uses: actions/cache@v4
        with:
          path: ${{ env.CCACHE_DIR }}
          key: stubs-${{ runner.os }}-${{ env.HOST }}-ccache-${{ github.run_id }}
          restore-keys: stubs-${{ runner.os }}-${{ env.HOST }}-ccache
      # Pip install dependencies
      - name: Install Python dependencies
        run: python3 -m pip install -U 'pip' 'build' 'conan' 'pybind11-stubgen~=2.5' 'numpy<3' 'py-build-cmake~=0.3.0a2'
      # Conan
      - name: Cache Conan
        uses: actions/cache@v4
        with:
          path: ${{ env.CONAN_HOME }}
          key: stubs-${{ runner.os }}-${{ env.HOST }}-conan-${{ github.run_id }}
          restore-keys: stubs-${{ runner.os }}-${{ env.HOST }}-conan
      - name: Install Conan
        run: |
          conan --version
          conan profile detect -f
          git clone https://github.com/tttapa/conan-recipes tttapa-conan-recipes
          conan remote add tttapa-conan-recipes tttapa-conan-recipes --force
      # Conan install dependencies
      - name: Install Conan dependencies
        run: |
          pfx="${{ steps.tools.outputs.install-dir }}"
          cat <<- EOF > python.profile
          include($pfx.python.profile.conan)
          [conf]
          tools.build:skip_test=true
          tools.build.cross_building:can_run=true
          tools.cmake.cmaketoolchain:generator=Ninja Multi-Config
          tools.cmake.cmake_layout:build_folder_vars=['const.python', 'settings.build_type']
          [buildenv]
          CFLAGS+= -fdiagnostics-color
          CXXFLAGS+= -fdiagnostics-color
          LDFLAGS+= -static-libgcc -static-libstdc++ -flto=auto
          EOF
          conan install . --build=missing \
            -pr:h python.profile \
            -o \&:with_ipopt=True -o \&:with_external_casadi=True \
            -o \&:with_qpalm=True -o \&:with_cutest=True \
            -o \&:with_python=True \
            -o "openblas/*:target=HASWELL" \
            -s build_type=Release
      # Build
      - name: Native build
        run: |
          pfx="${{ steps.tools.outputs.install-dir }}"
          py_majmin=$(python3 -c 'import sys; print(f"{sys.version_info.major}.{sys.version_info.minor}")')
          cat <<- EOF > cross.pbc
          os=linux
          toolchain_file=!  # Set by the Conan preset
          cmake.options.CMAKE_C_COMPILER_LAUNCHER="ccache"
          cmake.options.CMAKE_CXX_COMPILER_LAUNCHER="ccache"
          cmake.options.ALPAQA_WITH_PY_STUBS=true
          EOF
          py-build-cmake --version
          py-build-cmake --verbose \
            --local scripts/ci/py-build-cmake.toml \
            --cross $pfx.python$py_majmin.py-build-cmake.cross.toml \
            --cross cross.pbc \
            configure --index 20 \
            -- -D ALPAQA_INSTALL_PYSTUBSDIR="$PWD/stubs/python/alpaqa"
          py-build-cmake \
            --local scripts/ci/py-build-cmake.toml \
            --cross $pfx.python$py_majmin.py-build-cmake.cross.toml \
            --cross cross.pbc \
            build --index 20 -- -t python_modules
          py-build-cmake \
            --local scripts/ci/py-build-cmake.toml \
            --cross $pfx.python$py_majmin.py-build-cmake.cross.toml \
            --cross cross.pbc \
            install --index 20 --component python_modules \
            -- --prefix /tmp/_alpaqa
          py-build-cmake \
            --local scripts/ci/py-build-cmake.toml \
            --cross $pfx.python$py_majmin.py-build-cmake.cross.toml \
            --cross cross.pbc \
            install --index 20 --component python_stubs \
            -- --prefix /tmp/_alpaqa
          tar cf stubs.tar -C stubs python
      # Upload
      - name: Upload stubs
        uses: actions/upload-artifact@v4
        with:
          name: stubs
          retention-days: 1
          path: stubs.tar

  build-linux:
    needs: [generate-stubs]
    runs-on: ubuntu-latest
    container: 
      image: ubuntu:jammy
    strategy:
      matrix:
        python-version: ['3.13']
        host: [x86_64-bionic-linux-gnu]
    env:
      CMAKE_C_COMPILER_LAUNCHER: ccache
      CMAKE_CXX_COMPILER_LAUNCHER: ccache
      CCACHE_DIR: /root/.ccache
      CONAN_HOME: /root/.conan2
    steps:
      # Git clone
      - name: Install git
        run: apt -y update && apt -y install --no-install-recommends git ca-certificates
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      # Tools
      - name: Install tools
        id: tools
        uses: ./.github/workflows/new-toolchain
        with:
          host: ${{ matrix.host }}
          with-python: true
      # Ccache
      - name: Prepare ccache directory
        run: mkdir -p "${{ env.CCACHE_DIR }}"
      - name: Cache ccache
        uses: actions/cache@v4
        with:
          path: ${{ env.CCACHE_DIR }}
          key: python-${{ runner.os }}-${{ matrix.python-version }}-${{ matrix.host }}-ccache-${{ github.run_id }}
          restore-keys: python-${{ runner.os }}-${{ matrix.python-version }}-${{ matrix.host }}-ccache
      # Pip install dependencies
      - name: Install Python dependencies
        run: python${{ matrix.python-version }} -m pip install -U 'pip' 'build' 'conan'
      # Conan
      - name: Cache Conan
        uses: actions/cache@v4
        with:
          path: ${{ env.CONAN_HOME }}/p
          key: stubs-${{ runner.os }}-${{ matrix.host }}-conan-${{ github.run_id }}
          restore-keys: stubs-${{ runner.os }}-${{ matrix.host }}-conan
      - name: Install Conan
        run: |
          conan --version
          conan profile detect -f
          git clone https://github.com/tttapa/conan-recipes tttapa-conan-recipes
          conan remote add tttapa-conan-recipes tttapa-conan-recipes --force
      # Conan install dependencies
      - name: Install Conan dependencies
        run: |
          pfx="${{ steps.tools.outputs.install-dir }}"
          cat <<- EOF > python.profile
          include($pfx.python.profile.conan)
          [conf]
          tools.build:skip_test=true
          tools.cmake.cmaketoolchain:generator=Ninja Multi-Config
          tools.cmake.cmake_layout:build_folder_vars=['const.python', 'settings.build_type']
          [buildenv]
          CFLAGS+= -fdiagnostics-color
          CXXFLAGS+= -fdiagnostics-color
          LDFLAGS+= -static-libgcc -static-libstdc++ -flto=auto
          EOF
          case ${{ matrix.host }} in
              x86_64-bionic*) openblas_tgt="HASWELL" ;;
              aarch64-rpi3*) openblas_tgt="CORTEXA53" ;;
              armv8-rpi3*) openblas_tgt="CORTEXA15" ;;
              armv7-neon*) openblas_tgt="CORTEXA9" ;;
              armv6-rpi*) openblas_tgt="ARMV6" ;;
          esac
          for cfg in Debug Release; do
              conan install . --build=missing \
                  -pr:h python.profile \
                  -o \&:with_ipopt=False -o \&:with_external_casadi=False \
                  -o \&:with_qpalm=False -o \&:with_cutest=False \
                  -o \&:with_python=True \
                  -o "openblas/*:target=$openblas_tgt" \
                  -s "casadi/*:build_type=Release" \
                  -s build_type=$cfg
          done
      # Download stubs
      - name: Download stubs
        uses: actions/download-artifact@v4
        with:
          name: stubs
      - name: Extract stubs
        run: tar xf stubs.tar
      # Build
      - name: Build wheels
        run: |
          pfx="${{ steps.tools.outputs.install-dir }}"
          py_majmin=${{ matrix.python-version }}
          cat <<- EOF > cross.pbc
          os=linux
          toolchain_file=!  # Set by the Conan preset
          cmake.options.CMAKE_C_COMPILER_LAUNCHER="ccache"
          cmake.options.CMAKE_CXX_COMPILER_LAUNCHER="ccache"
          cmake.options.ALPAQA_WITH_PY_STUBS=false
          EOF
          python3 -m build -w \
            -C local=scripts/ci/py-build-cmake.toml \
            -C cross=$pfx.python$py_majmin.py-build-cmake.cross.toml \
            -C cross=cross.pbc
      - name: Build debug wheels
        if: ${{ matrix.host == 'x86_64-bionic-linux-gnu' }}
        run: |
          pfx="${{ steps.tools.outputs.install-dir }}"
          py_majmin=${{ matrix.python-version }}
          python3 -m build -w python/alpaqa-debug -o dist-debug \
            -C local=scripts/ci/py-build-cmake.toml \
            -C component=scripts/ci/py-build-cmake.component.toml \
            -C cross=$pfx.python$py_majmin.py-build-cmake.cross.toml \
            -C cross=cross.pbc
      # Upload
      - name: Upload Wheels
        uses: actions/upload-artifact@v4
        with:
          name: whl-linux-${{ matrix.python-version }}-${{ matrix.host }}
          retention-days: 1
          path: dist/*.whl
      - name: Upload debug Wheels
        if: ${{ matrix.host == 'x86_64-bionic-linux-gnu' }}
        uses: actions/upload-artifact@v4
        with:
          name: whl-debug-linux-${{ matrix.python-version }}-${{ matrix.host }}
          retention-days: 1
          path: dist-debug/*.whl

  build-linux-src:
    if: false
    runs-on: ubuntu-latest
    container:
      image: ubuntu:jammy
    env:
      HOST: 'x86_64-bionic-linux-gnu'
      PYTHON_VERSION: '3.11'
    steps:
      # Git clone
      - name: Install git
        run: apt -y update && apt -y install --no-install-recommends git ca-certificates
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      # Tools
      - name: Install tools
        uses: ./.github/workflows/toolchain
        with:
          host: ${{ env.HOST }}
          python-version: ${{ env.PYTHON_VERSION }}
          pypy: ''
      # Pip install dependencies
      - name: Install Python dependencies
        run: python${{ env.PYTHON_VERSION }} -m pip install -U pip build
      # Build
      - name: Build wheels
        run: |
          host="${{ env.HOST }}"
          staging="/opt/$host"
          cat > ninja-debug.cross.toml <<- EOF
          [cmake]
          build_args = ["1"]
          config = ["Debug"]
          generator = "Ninja Multi-Config"
          [cmake.options]
          CMAKE_FIND_ROOT_PATH = "$staging/pybind11-2.11.1;$staging/eigen-master;$staging/casadi"
          USE_GLOBAL_PYBIND11 = "On"
          ALPAQA_WITH_CUTEST = "On"
          ALPAQA_WITH_EXTERNAL_CASADI = "On"
          EOF
          python${{ env.PYTHON_VERSION }} -m build . \
              -C--cross="$PWD/ninja-debug.cross.toml" \
              -C--cross="$staging/$host.py-build-cmake.cross.toml"
        env:
          CXXFLAGS: '-static-libstdc++'
      # Upload
      - name: Upload source
        uses: actions/upload-artifact@v4
        with:
          name: src-dist
          retention-days: 1
          path: dist/*.tar.gz

  test-linux:
    if: false
    needs: [build-linux]
    runs-on: ubuntu-latest
    container: python:${{ matrix.python-version }}-bullseye
    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10', '3.11', '3.12']
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: actions/download-artifact@v4
        with:
          pattern: whl-linux-*
          merge-multiple: true
          path: dist
      - name: Test
        run: |
          python3 -m pip install -U pip cmake ninja
          python3 -m pip install --find-links=dist "${PACKAGE_NAME}[test]==${PACKAGE_VERSION}"
          pytest -rP


  build-windows:
    if: false
    needs: [generate-stubs]
    runs-on: windows-2022
    strategy:
      matrix:
        arch: ['AMD64', 'ARM64', 'x86']
        python-id: ['cp38-', 'cp39-', 'cp310-', 'cp311-', 'cp312-']
        exclude:
          - arch: 'ARM64'
            python-id: 'cp38-'
    env:
      CXXFLAGS: "/bigobj"
      CFLAGS: "/bigobj"
      PYTHONUTF8: 1
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Cache dependencies
        id: cache-dep
        uses: actions/cache@v4
        with:
          path: deps
          key: deps-${{ runner.os }}-${{ matrix.arch }}-${{ hashFiles('scripts/install-eigen.ps1', 'scripts/install-casadi-static.ps1') }}
      - name: Install Python dependencies
        if: steps.cache-dep.outputs.cache-hit != 'true'
        shell: powershell
        run: |
          mkdir $env:VIRTUAL_ENV
          ./scripts/install-eigen.ps1
          ./scripts/install-casadi-static.ps1
        env:
          VIRTUAL_ENV: ${{ github.workspace }}/deps
          CMAKE_TOOLCHAIN_FILE: ${{ github.workspace }}/scripts/toolchains/Win-${{ matrix.arch }}.cmake
      # Download stubs
      - name: Download stubs
        if: ${{ matrix.arch == 'ARM64' }}
        uses: actions/download-artifact@v4
        with:
          name: stubs
      - name: Extract stubs
        if: ${{ matrix.arch == 'ARM64' }}
        run: tar xf stubs.tar
      - name: Disable Fortran
        run: |
          cat > py-build-cmake.local.toml <<- EOF
          [cmake.options]
          CMAKE_Fortran_COMPILER = "NOTFOUND"
          ALPAQA_WITH_EXTERNAL_CASADI = "On"
          EOF
        shell: bash
      - name: Build wheels
        uses: pypa/cibuildwheel@8d945475ac4b1aac4ae08b2fd27db9917158b6ce
        with:
          output-dir: dist
        env:
          CIBW_BUILD: "${{ matrix.python-id }}*"
          CIBW_ARCHS: ${{ matrix.arch }}
          CIBW_TEST_SKIP: "*-{win32,win_arm64} pp*" # no CasADi binaries
          CMAKE_PREFIX_PATH: ${{ github.workspace }}/deps
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: whl-windows-${{ matrix.python-id }}-${{ matrix.arch }}
          retention-days: 1
          path: dist/*.whl


  build-macos:
    if: false
    runs-on: macos-13
    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10', '3.11', '3.12']
    env:
      CMAKE_C_COMPILER_LAUNCHER: ccache
      CMAKE_CXX_COMPILER_LAUNCHER: ccache
      CCACHE_DIR: /tmp/.ccache
      DEVELOPER_DIR: /Applications/Xcode_15.2.app/Contents/Developer
      MACOSX_DEPLOYMENT_TARGET: '10.15'
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: actions/setup-python@v5
        id: python
        name: Install Python
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install ccache
        run: brew install ccache && ccache --version
      - name: Prepare ccache directory
        run: mkdir -p "${{ env.CCACHE_DIR }}"
      - name: Cache ccache
        uses: actions/cache@v4
        with:
          path: ${{ env.CCACHE_DIR }}
          key: ${{ runner.os }}-${{ matrix.python-version }}-ccache-${{ github.run_id }}
          restore-keys: ${{ runner.os }}-${{ matrix.python-version }}-ccache
      - name: Cache Virtual Environment
        id: cache-venv
        uses: actions/cache@v4
        with:
          path: py-venv
          key: ${{ runner.os }}-${{ steps.python.outputs.python-version }}-${{ hashFiles('scripts/install-eigen.sh', 'scripts/install-casadi-static.sh') }}
      - name: Install Python dependencies 
        if: steps.cache-venv.outputs.cache-hit != 'true'
        run: |
          python -m venv py-venv
          source ./py-venv/bin/activate
          python -m pip install -U pip build cmake ninja
          ./scripts/install-eigen.sh
          ./scripts/install-casadi-static.sh
      - name: Disable Fortran
        run: |
          cat > py-build-cmake.local.toml <<- EOF
          [cmake.options]
          CMAKE_Fortran_COMPILER = "NOTFOUND"
          ALPAQA_WITH_EXTERNAL_CASADI = "On"
          EOF
        shell: bash
      - name: Build
        run: |
          source ./py-venv/bin/activate
          CMAKE_PREFIX_PATH="$VIRTUAL_ENV:$CMAKE_PREFIX_PATH" \
          _PYTHON_HOST_PLATFORM='macosx-10.15-universal2' \
          ARCHFLAGS='-arch arm64 -arch x86_64' \
              python -m build -w .
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: whl-macos-${{ matrix.python-version }}
          retention-days: 1
          path: dist/*.whl

  test-macos:
    if: false
    needs: [build-macos]
    runs-on: macos-12
    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10', '3.11']
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: actions/setup-python@v5
        name: Install Python
        with: 
          python-version: ${{ matrix.python-version }}
      - uses: actions/download-artifact@v4
        with:
          name: whl-macos-${{ matrix.python-version }}
          path: dist
      - name: Test
        run: |
          python3 -m pip install -U pip cmake ninja
          python3 -m pip install --find-links=dist "${PACKAGE_NAME}[test]==${PACKAGE_VERSION}"
          pytest -rP


  check-release:
    if: ${{ github.event.action == 'released' || github.event.action == 'prereleased' }}
    needs: [test-linux, build-linux-src, build-windows, test-macos]
    runs-on: ubuntu-latest
    container: python:3.11-bullseye
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          pattern: whl-linux-*
          merge-multiple: true
          path: dist
      - name: Install package
        run: python -m pip install --no-deps --no-index --find-links=dist ${PACKAGE_NAME}==${PACKAGE_VERSION}
      - name: Check package version
        run: |
          [ "${{ github.event.release.tag_name }}" == $(python -c 'from importlib.metadata import version as v; print(v("${{ env.PACKAGE_NAME }}"))') ]
        shell: bash

  release:
    needs: [check-release]
    if: ${{ github.event.action == 'released' || github.event.action == 'prereleased' }}
    runs-on: ubuntu-latest
    environment:
      name: release
      url: https://pypi.org/p/alpaqa
    permissions:
      id-token: write  # mandatory for trusted publishing
    steps:
      - uses: actions/download-artifact@v4
        with:
          pattern: whl-linux-*
          merge-multiple: true
          path: dist
      - uses: actions/download-artifact@v4
        with:
          pattern: whl-debug-linux-*
          merge-multiple: true
          path: dist
      - uses: actions/download-artifact@v4
        with:
          pattern: whl-windows-*
          merge-multiple: true
          path: dist
      - uses: actions/download-artifact@v4
        with:
          pattern: whl-macos-*
          merge-multiple: true
          path: dist
      - uses: actions/download-artifact@v4
        with:
          name: src-dist
          path: dist
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@2f6f737ca5f74c637829c0f5c3acd0e29ea5e8bf
